### ISSUE TITLE
trait bound `H256: TypeInfo` is not satisfied; `TypeInfo` is not implemented for `H256, H160, H64, ethereum_types::U256`

### ISSUE THREAD

**Issue by AuroraLantean** [paritytech/scale-info#153]
[](https://substrate.stackexchange.com/posts/1878/timeline)Frontier(pallet-ethereum) project failed to compile after updating from polkadot-v0.9.17 to v0.9.18

```
   Compiling polkadot-runtime v0.9.18 (https://github.com/paritytech/polkadot?branch=release-v0.9.18#9ed0c982)
   Compiling kusama-runtime v0.9.18 (https://github.com/paritytech/polkadot?branch=release-v0.9.18#9ed0c982)
   Compiling p-chain-runtime v0.0.1 (/mnt/sda3/polkadot/1pchain/runtime)
    Checking ethereum v0.12.0
error[E0277]: the trait bound `H256: TypeInfo` is not satisfied
   --> /home/user2038/.cargo/registry/src/github.com-1ecc6299db9ec823/ethereum-0.12.0/src/header.rs:10:39
    |
10  |     derive(codec::Encode, codec::Decode, scale_info::TypeInfo)
    |                                          ^^^^^^^^^^^^^^^^^^^^ the trait `TypeInfo` is not implemented for `H256`
    |
note: required by a bound in `FieldBuilder::<N>::ty`
   --> /home/user2038/.cargo/registry/src/github.com-1ecc6299db9ec823/scale-info-2.1.1/src/build.rs:382:13
    |
382 |         TY: TypeInfo + 'static + ?Sized,
    |             ^^^^^^^^ required by this bound in `FieldBuilder::<N>::ty`
    = note: this error originates in the derive macro `scale_info::TypeInfo` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `H160: TypeInfo` is not satisfied
   --> /home/user2038/.cargo/registry/src/github.com-1ecc6299db9ec823/ethereum-0.12.0/src/header.rs:10:39
    |
10  |     derive(codec::Encode, codec::Decode, scale_info::TypeInfo)
    |                                          ^^^^^^^^^^^^^^^^^^^^ the trait `TypeInfo` is not implemented for `H160`
    |
note: required by a bound in `FieldBuilder::<N>::ty`
   --> /home/user2038/.cargo/registry/src/github.com-1ecc6299db9ec823/scale-info-2.1.1/src/build.rs:382:13
    |
382 |         TY: TypeInfo + 'static + ?Sized,
    |             ^^^^^^^^ required by this bound in `FieldBuilder::<N>::ty`
    = note: this error originates in the derive macro `scale_info::TypeInfo` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `Bloom: TypeInfo` is not satisfied
   --> /home/user2038/.cargo/registry/src/github.com-1ecc6299db9ec823/ethereum-0.12.0/src/header.rs:10:39
    |
10  |     derive(codec::Encode, codec::Decode, scale_info::TypeInfo)
    |                                          ^^^^^^^^^^^^^^^^^^^^ the trait `TypeInfo` is not implemented for `Bloom`
    |
note: required by a bound in `FieldBuilder::<N>::ty`
   --> /home/user2038/.cargo/registry/src/github.com-1ecc6299db9ec823/scale-info-2.1.1/src/build.rs:382:13
    |
382 |         TY: TypeInfo + 'static + ?Sized,
    |             ^^^^^^^^ required by this bound in `FieldBuilder::<N>::ty`
    = note: this error originates in the derive macro `scale_info::TypeInfo` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `ethereum_types::U256: TypeInfo` is not satisfied
   --> /home/user2038/.cargo/registry/src/github.com-1ecc6299db9ec823/ethereum-0.12.0/src/header.
```

My Rust tool-chain

```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/user2038/.rustup
installed toolchains
stable-x86_64-unknown-linux-gnu
nightly-2021-09-10-x86_64-unknown-linux-gnu
nightly-2021-11-12-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
bpf
1.59.0-x86_64-unknown-linux-gnu (default)

active toolchain
1.59.0-x86_64-unknown-linux-gnu (default)
rustc 1.59.0 (9d1b2106e 2022-02-23)
```

**Comment by jsdw** [comment]
Offhand, I'd try running a `cargo tree` on your codebase. It may well be that there are now two versions of `scale-info` in your dependency tree, and if that is true, the errors may be because the `TypeInfo` have been implemented against one version but not the other.

**Comment by ascjones** [comment]
Yes this looks like mismatching versions. `cargo tree -p scale-info` will show you.

`ethereum-types` has very permissive requirements for `scale-info`, so maybe a `cargo update -p scale-info` will fix the mismatch.

**Comment by AuroraLantean** [comment]
@jsdw here is my cargo tree: https://gist.github.com/AuroraLantean/26436567673311ee6ee8db5efcdb8675
It is too large to put it here. 
$ cargo tree -p scale-info:1.0.0
```
scale-info v1.0.0
├── cfg-if v1.0.0
├── derive_more v0.99.17 (proc-macro)
│   ├── convert_case v0.4.0
│   ├── proc-macro2 v1.0.36
│   │   └── unicode-xid v0.2.2
│   ├── quote v1.0.18
│   │   └── proc-macro2 v1.0.36 (*)
│   └── syn v1.0.89
│       ├── proc-macro2 v1.0.36 (*)
│       ├── quote v1.0.18 (*)
│       └── unicode-xid v0.2.2
│   [build-dependencies]
│   └── rustc_version v0.4.0
│       └── semver v1.0.6
│           └── serde v1.0.136
│               └── serde_derive v1.0.136 (proc-macro)
│                   ├── proc-macro2 v1.0.36 (*)
│                   ├── quote v1.0.18 (*)
│                   └── syn v1.0.89 (*)
├── parity-scale-codec v2.3.1
│   ├── arrayvec v0.7.2
│   ├── byte-slice-cast v1.2.1
│   ├── impl-trait-for-tuples v0.2.2 (proc-macro)
│   │   ├── proc-macro2 v1.0.36 (*)
│   │   ├── quote v1.0.18 (*)
│   │   └── syn v1.0.89 (*)
│   └── parity-scale-codec-derive v2.3.1 (proc-macro)
│       ├── proc-macro-crate v1.1.3
│       │   ├── thiserror v1.0.30
│       │   │   └── thiserror-impl v1.0.30 (proc-macro)
│       │   │       ├── proc-macro2 v1.0.36 (*)
│       │   │       ├── quote v1.0.18 (*)
│       │   │       └── syn v1.0.89 (*)
│       │   └── toml v0.5.8
│       │       └── serde v1.0.136 (*)
│       ├── proc-macro2 v1.0.36 (*)
│       ├── quote v1.0.18 (*)
│       └── syn v1.0.89 (*)
└── scale-info-derive v1.0.0 (proc-macro)
    ├── proc-macro-crate v1.1.3 (*)
    ├── proc-macro2 v1.0.36 (*)
    ├── quote v1.0.18 (*)
    └── syn v1.0.89 (*)
```

$ cargo tree -p scale-info:2.1.1
```
scale-info v2.1.1
├── bitvec v1.0.0
│   ├── funty v2.0.0
│   ├── radium v0.7.0
│   ├── tap v1.0.1
│   └── wyz v0.5.0
│       └── tap v1.0.1
├── cfg-if v1.0.0
├── derive_more v0.99.17 (proc-macro)
│   ├── convert_case v0.4.0
│   ├── proc-macro2 v1.0.36
│   │   └── unicode-xid v0.2.2
│   ├── quote v1.0.18
│   │   └── proc-macro2 v1.0.36 (*)
│   └── syn v1.0.89
│       ├── proc-macro2 v1.0.36 (*)
│       ├── quote v1.0.18 (*)
│       └── unicode-xid v0.2.2
│   [build-dependencies]
│   └── rustc_version v0.4.0
│       └── semver v1.0.6
│           └── serde v1.0.136
│               └── serde_derive v1.0.136 (proc-macro)
│                   ├── proc-macro2 v1.0.36 (*)
│                   ├── quote v1.0.18 (*)
│                   └── syn v1.0.89 (*)
├── parity-scale-codec v3.1.2
│   ├── arrayvec v0.7.2
│   ├── bitvec v1.0.0 (*)
│   ├── byte-slice-cast v1.2.1
│   ├── impl-trait-for-tuples v0.2.2 (proc-macro)
│   │   ├── proc-macro2 v1.0.36 (*)
│   │   ├── quote v1.0.18 (*)
│   │   └── syn v1.0.89 (*)
│   ├── parity-scale-codec-derive v3.1.2 (proc-macro)
│   │   ├── proc-macro-crate v1.1.3
│   │   │   ├── thiserror v1.0.30
│   │   │   │   └── thiserror-impl v1.0.30 (proc-macro)
│   │   │   │       ├── proc-macro2 v1.0.36 (*)
│   │   │   │       ├── quote v1.0.18 (*)
│   │   │   │       └── syn v1.0.89 (*)
│   │   │   └── toml v0.5.8
│   │   │       └── serde v1.0.136 (*)
│   │   ├── proc-macro2 v1.0.36 (*)
│   │   ├── quote v1.0.18 (*)
│   │   └── syn v1.0.89 (*)
│   └── serde v1.0.136 (*)
├── scale-info-derive v2.1.1 (proc-macro)
│   ├── proc-macro-crate v1.1.3 (*)
│   ├── proc-macro2 v1.0.36 (*)
│   ├── quote v1.0.18 (*)
│   └── syn v1.0.89 (*)
└── serde v1.0.136 (*)

```
@ascjones yes I found two scale-info versions via `cargo tree -p scale-info`
```
error: There are multiple `scale-info` packages in your project, and the specification `scale-info` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  scale-info:1.0.0
  scale-info:2.1.1
```

Then I tried `cargo update -p scale-info:2.1.1`
`    Updating crates.io index
`
That does not solve the error. Same error continues...
Then I tried `cargo update -p scale-info:1.0.0`
```
    Updating crates.io index
    Removing parity-scale-codec v2.3.1
    Removing parity-scale-codec-derive v2.3.1
    Removing scale-info v1.0.0
    Removing scale-info-derive v1.0.0

```
That seems to be working...
Then I got a new error:
```
error: failed to run custom build command for `paid-chain-runtime v0.0.1 (/mnt/sda3/polkadot/1paidchain/runtime)`

Caused by:
  process didn't exit successfully: `/mnt/sda3/polkadot/1paidchain/target/debug/build/paid-chain-runtime-ad3de5054f3ba2f0/build-script-build` (exit status: 1)
  --- stdout
  Information that should be included in a bug report.
  Executing build command: "rustup" "run" "nightly" "cargo" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=/mnt/sda3/polkadot/1paidchain/target/debug/wbuild/paid-chain-runtime/Cargo.toml" "--color=always" "--profile" "release"
  Using rustc version: rustc 1.62.0-nightly (52ca603da 2022-04-12)
  --- stderr
  warning: Patch `fc-db v2.0.0-dev (https://github.com/AuroraLantean/frontier-mod?branch=polkadot-v0.9.18#e2ecbd52)` was not used in the crate graph.
  Patch `fc-mapping-sync v2.0.0-dev (https://github.com/AuroraLantean/frontier-mod?branch=polkadot-v0.9.18#e2ecbd52)` was not used in the crate graph.
  Patch `fc-rpc v2.0.0-dev (https://github.com/AuroraLantean/frontier-mod?branch=polkadot-v0.9.18#e2ecbd52)` was not used in the crate graph.
  Patch `fc-rpc-core v1.1.0-dev (https://github.com/AuroraLantean/frontier-mod?branch=polkadot-v0.9.18#e2ecbd52)` was not used in the crate graph.
  Check that the patched package version and available features are compatible
  with the dependency requirements. If the patch has a different version from
  what is locked in the Cargo.lock file, run `cargo update` to use the new
  version. This may also occur with an optional dependency that is not enabled.
```
...
```
 error[E0046]: not all trait items implemented, missing: `WeightInfo`
     --> /mnt/sda3/polkadot/1paidchain/runtime/src/lib.rs:607:1
      |
  607 | impl cumulus_pallet_xcmp_queue::Config for Runtime {
      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `WeightInfo` in implementation
      |
      = help: implement the missing item: `type WeightInfo = Type;`

  For more information about this error, try `rustc --explain E0046`.
```
Any advice? Thank you so much
